### ISSUE TITLE
Configurable game executable name

### ISSUE THREAD

**Issue by chicouskiluiz** [flipdeezy/SFSE_WeaponModelFOV#3]
Is there a possibility to make the name of the game's executable dynamic, within the .ini file? By default it tries to access "Starfield.exe", if possible I would like it to load "starfieldgame.exe". To start SFSE directly through Steam, I renamed my Starfield and SFSE executables, looking like this:
Starfield.exe -> starfieldgame.exe
sfse_loader.exe -> Starfield.exe
And I configured the new name of the game's executable within sfse.ini.

**Comment by flipdeezy** [comment]
This issue was resovled in the latest update. I no lonfer get the base address from the exe
